package app

type RouterGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	AppUserRouter
	AppSetRouter
	AppMchRouter
	AppPayRouter
	AppCategoryRouter
	AppAgreementRouter
	AppStoreRouter
	AppRelieveStoreRouter
	AppFeedbackRouter
	AppNoticeRouter
	AppServiceRouter
	AppUrlRouter
	AppFacilitatingAgencyRouter
	AppCustInfoRouter
	AppAreaInfoRouter
	AppUploadImgRouter
	AppSignContractRouter
	AppWechatCertificationRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
