package app

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	AppUserApi
	AppSetApi
	AppMchApi
	AppPayApi
	AppCategoryApi
	AppAgreementApi
	AppStoreApi
	AppRelieveStoreApi
	AppFeedbackApi
	AppNoticeApi
	AppServiceApi
	AppUrlApi
	AppFacilitatingAgencyApi
	AppCustInfoApi
	AppAreaInfoApi
	AppUploadImgApi
	AppSignContractApi
	AppWechatCertificationApi
	AppAlipayCertificationApi
	AppOrderPayApi
	AppRateApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
