package app

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	AppUserService
	AppSetService
	AppMchService
	AppPayService
	AppCategoryService
	AppAgreementService
	AppStoreService
	AppRelieveStoreService
	AppFeedbackService
	AppNoticeService
	AppServiceService
	AppUrlService
	AppFacilitatingAgencyService
	AppCustInfoService
	AppAreaInfoService
	AppUploadImgService
	AppSignContractService
	AppWechatCertificationService
	AppAlipayCertificationService
	AppOrderPayService
	AppRateService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}

const (
	USER_ZERO  = 0 //未认证
	USER_ONE   = 1 //审核中
	USER_TWO   = 2 //认证成功
	USER_THREE = 3 //认证未通过

	//商户及支付认证状态
	STATE_ONE   = 1 //未通过
	STATE_TWO   = 2 //已通过
	STATE_THREE = 3 //已拒绝

	MCH_STATE = "mchState"
	PAY_STATE = "payState"
)

type BusinessData struct {
	SysFlowId                string `json:"sysFlowId"`
	Status                   string `json:"status"`
	CustId                   string `json:"custId"`
	SignUrl                  string `json:"signUrl"`            //签约地址
	SignId                   string `json:"signId"`             //签约Id
	AuthId                   string `json:"authId"`             //权限ID
	MercId                   string `json:"mercId"`             //子商户号
	State                    string `json:"state"`              //交易状态
	ApplyNo                  string `json:"applyNo"`            //申请单编号
	SendChannelApplyNo       string `json:"sendChannelApplyNo"` //业务编号
	ApplyState               string `json:"applyState"`         //申请单状态
	RejectParam              string `json:"rejectParam"`
	RejectReason             string `json:"rejectReason"`
	ReqMsgId                 string `json:"reqMsgId"`
	Url                      string `json:"url"`                      //文件url地址,上传文件返回的url地址
	DocumentId               string `json:"documentId"`               //document表ID,此返回值无需处理
	ChangeSysFlowId          string `json:"changeSysFlowId"`          //变更申请流水号
	SendChannelAuthApplyId   string `json:"sendChannelAuthApplyId"`   //实名认证申请单编号,银盛系统生成的申请单编号
	ApplyStatus              string `json:"applyStatus"`              //申请单审核状态
	QrcodePic                string `json:"qrcodePic"`                //小程序码图片,fastDfs上的图片地址
	QrcodeData               string `json:"qrcodeData"`               //小程序码图片,base64编码
	OutMercIdAuthStatus      string `json:"outMercIdAuthStatus"`      //授权状态,第三方商户号授权状态
	OutMercIdRemark          string `json:"outMercIdRemark"`          //授权状态备注,第三方商户号授权状态备注
	AuthTime                 string `json:"authTime"`                 //授权认证时间,格式：yyyyMMddHHmmss
	ChannelReturnAuthApplyId string `json:"channelReturnAuthApplyId"` //渠道申请单编号,渠道返回实名认证申请单编号
	AuthState                string `json:"authState"`                //授权状态,0-未授权；1-已授权；2-已销户

	ThirdMercIdX string `json:"thirdMercIdX"` //第三方商户号1
	AuthStateX   string `json:"authStateX"`   //授权状态,AUTHORIZE_STATE_UNAUTHORIZED：未授权 AUTHORIZE_STATE_AUTHORIZED：已授权
	ThirdMercIdY string `json:"thirdMercIdY"` //第三方商户号2,上送商户号可能对应微信的1个或2个第三方商户号，所以当有两个第三方商户的时候thirdMercIdY，authStateY会有值
	AuthStateY   string `json:"authStateY"`   //	授权状态2,AUTHORIZE_STATE_UNAUTHORIZED：未授权  AUTHORIZE_STATE_AUTHORIZED：已授权)
}
type YsResult struct {
	Code         string       `json:"code"`
	Msg          string       `json:"msg"`
	SubCode      string       `json:"subCode"`
	SubMsg       string       `json:"subMsg"`
	SysFlowId    string       `json:"sysFlowId"`
	BusinessData BusinessData `json:"businessData"`
}

//地区信息
type AreaInfo struct {
	CityCd       string `json:"cityCd"`
	AreaCode     string `json:"areaCode"`
	IsAble       string `json:"isAble"`
	CityNm       string `json:"cityNm"`
	AreaLevel    string `json:"areaLevel"`
	ParentCityCd string `json:"parentCityCd"`
}

//商户余额查询返回数据
//业务响应参数的集合，最大长度不限
type BalanceQueryResult struct {
	Code                       string          `json:"code"`
	Msg                        string          `json:"msg"`
	AccountTotalAmount         string          `json:"account_total_amount"`
	AccountSettledUnpaidAmount string          `json:"account_settled_unpaid_amount"`
	AccountDetail              []AccountDetail `json:"account_detail"`
}

// 账户明细 account_detail
type AccountDetail struct {
	AccountId              string `json:"account_id"`
	AccountType            string `json:"account_type"`
	AccountAmount          string `json:"account_amount"`
	AccountWithdrawbalance string `json:"account_withdrawbalance"`
}

//微信支付返回的参数
type WechatPayResult struct {
	Code         string `json:"code"`
	Msg          string `json:"msg"`
	TradeStatus  string `json:"trade_status"`
	OutTradeNo   string `json:"out_trade_no"`
	JsapiPayInfo string `json:"jsapi_pay_info"`
}

type JsapiPayInfo struct {
	Appid     string `json:"appId"`
	TimeStamp string `json:"timeStamp"`
	NonceStr  string `json:"nonceStr"`
	Package   string `json:"package"`
	SignType  string `json:"signType"`
	PaySign   string `json:"paySign"`
	OrderNo   string `json:"orderNo"`
}

//支付宝支付返回的参数
type AliPayResult struct {
	Code         string `json:"code"`
	Msg          string `json:"msg"`
	OutTradeNo   string `json:"out_trade_no"`
	TradeStatus  string `json:"trade_status"`
	TotalAmount  string `json:"total_amount"`
	JsapiPayInfo string `json:"jsapi_pay_info"`
}

type AliPayInfoResult struct {
	TradeNo string `json:"tradeNo"`
	Status  string `json:"status"`
	OrderNo string `json:"orderNo"`
}

//请求Php的基本域名
var BaseUrl = "http://jiyunbao.vvv5g.com/"
